<?php

namespace App\Connectors;

use App\Models\ConnectorInstance;
use RuntimeException;

/**
 * Pelican Panel genuinely has two separate API surfaces with two separate
 * key types (confirmed against real docs and a real third-party
 * integration — not assumed):
 *
 * - Application API (/api/application/*) — admin-scoped, an "Application
 *   API Key" generated by an admin. Sees and manages every server on the
 *   panel regardless of who owns it. This is what real server discovery
 *   needs — the Client API's own list endpoint only shows servers owned by
 *   whichever user account issued that key.
 * - Client API (/api/client/*) — user-scoped, a "Client API Key" generated
 *   by a regular user. Live per-server data (resource stats, console)
 *   lives only here; the Application API doesn't expose it.
 *
 * credentials = {"application_token": "...", "client_token": "..."} —
 * client_token is optional (only needed for fetch(), not listServers()).
 */
class PelicanConnector implements ConnectorContract
{
    public function __construct(
        protected HttpRequestContract $http,
    ) {}

    public static function type(): string
    {
        return 'pelican';
    }

    /**
     * Live resource stats for one server — Client API only.
     */
    public function fetch(ConnectorInstance $instance, array $callConfig): array
    {
        $serverIdentifier = $callConfig['server_identifier']
            ?? throw new RuntimeException('Pelican calls require a "server_identifier" in the binding config.');

        $token = $instance->credentials['client_token'] ?? null;

        if (! $token) {
            throw new RuntimeException(
                "Connector instance [{$instance->name}] has no Client API Key configured — needed for live resource stats."
            );
        }

        return $this->request($instance, "/api/client/servers/{$serverIdentifier}/resources", $token);
    }

    /**
     * Every server on the panel, regardless of owner — Application API
     * only. This is the auto-discovery Pelican makes possible: an admin
     * picks a server identifier from a real list instead of typing one
     * blind.
     *
     * @return array<int, array{identifier: string, name: string}>
     */
    public function listServers(ConnectorInstance $instance): array
    {
        $token = $instance->credentials['application_token'] ?? null;

        if (! $token) {
            throw new RuntimeException(
                "Connector instance [{$instance->name}] has no Application API Key configured — needed to list servers."
            );
        }

        $data = $this->request($instance, '/api/application/servers', $token);

        return collect($data['data'] ?? [])
            ->map(fn (array $entry) => [
                'identifier' => $entry['attributes']['identifier'] ?? '',
                'name' => $entry['attributes']['name'] ?? '(unnamed)',
            ])
            ->filter(fn (array $server) => $server['identifier'] !== '')
            ->values()
            ->all();
    }

    protected function request(ConnectorInstance $instance, string $path, string $token): array
    {
        $url = rtrim($instance->base_url, '/').'/'.ltrim($path, '/');

        $response = $this->http->request('GET', $url, [
            'Accept' => 'Application/vnd.pterodactyl.v1+json',
            'Authorization' => "Bearer {$token}",
        ]);

        if ($response['status'] < 200 || $response['status'] >= 300) {
            throw new RuntimeException("Pelican call to [{$url}] returned HTTP {$response['status']}.");
        }

        $data = json_decode($response['body'], true);

        if (! is_array($data)) {
            throw new RuntimeException("Pelican call to [{$url}] did not return valid JSON.");
        }

        return $data;
    }
}
