<?php

namespace App\Filament\Resources;

use App\Connectors\PelicanConnector;
use App\Connectors\RestConnector;
use App\Filament\Resources\ConnectorInstanceResource\Pages;
use App\Models\ConnectorInstance;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Throwable;

class ConnectorInstanceResource extends Resource
{
    protected static ?string $model = ConnectorInstance::class;

    protected static ?string $navigationIcon = 'heroicon-o-bolt';

    protected static ?string $navigationGroup = 'Capabilities';

    protected static ?string $navigationLabel = 'Connectors';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Connection')
                    ->description(
                        'A credentialed connection to one external system — e.g. one Palworld '
                        .'server\'s REST API, or one Pelican panel. Use it as a provider under a '
                        .'Server\'s edit page → Providers.'
                    )
                    ->schema([
                        Forms\Components\TextInput::make('name')
                            ->required()
                            ->maxLength(255)
                            ->helperText('e.g. "EU-1 Palworld REST API".'),
                        Forms\Components\Select::make('type')
                            ->options([
                                'rest' => 'Generic REST (Basic/Bearer/API-key auth)',
                                'pelican' => 'Pelican Panel (Application + Client API)',
                            ])
                            ->required()
                            ->live(),
                        Forms\Components\TextInput::make('base_url')
                            ->label('Base URL')
                            ->required()
                            ->url()
                            ->helperText(fn (Forms\Get $get) => match ($get('type')) {
                                'pelican' => 'Your Pelican panel URL, e.g. https://panel.example.com',
                                default => 'e.g. http://your-server-ip:8212 for Palworld\'s REST API',
                            }),
                        Forms\Components\TextInput::make('test_endpoint')
                            ->label('Test endpoint')
                            ->visible(fn (Forms\Get $get) => $get('type') === 'rest')
                            ->helperText(
                                'A lightweight GET endpoint used only by "Test Connection" to check auth/'
                                .'reachability — e.g. "/v1/api/info" for Palworld. Not used by capability bindings.'
                            ),
                        Forms\Components\TextInput::make('poll_interval_seconds')
                            ->label('Auto-refresh every (seconds)')
                            ->numeric()
                            ->minValue(5)
                            ->default(30)
                            ->required()
                            ->helperText('How often the background poller re-checks servers using this connector.'),
                        Forms\Components\Select::make('status')
                            ->options([
                                'untested' => 'Untested',
                                'ok' => 'OK',
                                'error' => 'Error',
                            ])
                            ->default('untested')
                            ->required()
                            ->disabled()
                            ->dehydrated()
                            ->helperText('Set automatically by "Test Connection" / "Discover Servers" — not hand-edited.'),
                        Forms\Components\TextInput::make('pelican_application_token')
                            ->label('Application API Key')
                            ->password()
                            ->revealable()
                            ->visible(fn (Forms\Get $get) => $get('type') === 'pelican')
                            ->helperText(
                                'Admin-scoped — generated by an admin under Admin → API Credentials. Sees every '
                                .'server on the panel regardless of owner. Required for "Discover Servers".'
                            ),
                        Forms\Components\TextInput::make('pelican_client_token')
                            ->label('Client API Key (optional)')
                            ->password()
                            ->revealable()
                            ->visible(fn (Forms\Get $get) => $get('type') === 'pelican')
                            ->helperText(
                                'User-scoped — generated under Account Settings → API Credentials by a user who '
                                .'owns the server(s) you want live stats for. Only needed for server-status data, '
                                .'not for discovery.'
                            ),
                        Forms\Components\Select::make('rest_auth_style')
                            ->label('Authentication')
                            ->options([
                                'basic' => 'Username + Password (e.g. Palworld: username "admin", password = AdminPassword)',
                                'bearer' => 'Bearer Token',
                            ])
                            ->default('basic')
                            ->live()
                            ->visible(fn (Forms\Get $get) => $get('type') === 'rest'),
                        Forms\Components\TextInput::make('rest_username')
                            ->label('Username')
                            ->visible(fn (Forms\Get $get) => $get('type') === 'rest' && $get('rest_auth_style') === 'basic'),
                        Forms\Components\TextInput::make('rest_password')
                            ->label('Password')
                            ->password()
                            ->revealable()
                            ->visible(fn (Forms\Get $get) => $get('type') === 'rest' && $get('rest_auth_style') === 'basic'),
                        Forms\Components\TextInput::make('rest_token')
                            ->label('Bearer Token')
                            ->password()
                            ->revealable()
                            ->visible(fn (Forms\Get $get) => $get('type') === 'rest' && $get('rest_auth_style') === 'bearer'),
                        Forms\Components\KeyValue::make('discovered_servers_display')
                            ->label('Discovered servers (UUIDs)')
                            ->visible(fn (Forms\Get $get) => $get('type') === 'pelican' && filled($get('discovered_servers_display')))
                            ->disabled()
                            ->dehydrated(false)
                            ->keyLabel('UUID')
                            ->valueLabel('Name')
                            ->helperText('From the last "Discover Servers" run. Click that action again to refresh.')
                            ->columnSpanFull(),
                    ])
                    ->columns(2),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('type')
                    ->badge(),
                Tables\Columns\TextColumn::make('base_url')
                    ->label('Base URL'),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'ok' => 'success',
                        'error' => 'danger',
                        default => 'gray',
                    }),
                Tables\Columns\TextColumn::make('discovered_servers')
                    ->label('Discovered')
                    ->formatStateUsing(function ($state) {
                        $servers = is_string($state) ? json_decode($state, true) : $state;

                        return filled($servers) ? count($servers).' server(s)' : '—';
                    })
                    ->toggleable(),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('type')
                    ->options([
                        'rest' => 'Generic REST',
                        'pelican' => 'Pelican Panel',
                    ]),
            ])
            ->actions([
                Tables\Actions\Action::make('testConnection')
                    ->label('Test connection')
                    ->icon('heroicon-o-signal')
                    ->visible(fn (ConnectorInstance $record) => $record->type === 'rest')
                    ->action(function (ConnectorInstance $record, RestConnector $rest): void {
                        try {
                            $rest->fetch($record, ['endpoint' => $record->test_endpoint ?: '/']);
                        } catch (Throwable $e) {
                            $record->update(['status' => 'error']);

                            Notification::make()
                                ->title('Connection failed')
                                ->body($e->getMessage())
                                ->danger()
                                ->send();

                            return;
                        }

                        $record->update(['status' => 'ok']);

                        Notification::make()
                            ->title('Connection OK')
                            ->body("Reached {$record->base_url} and got a valid JSON response.")
                            ->success()
                            ->send();
                    }),
                Tables\Actions\Action::make('discoverServers')
                    ->label('Discover servers')
                    ->icon('heroicon-o-magnifying-glass')
                    ->visible(fn (ConnectorInstance $record) => $record->type === 'pelican')
                    ->action(function (ConnectorInstance $record, PelicanConnector $pelican): void {
                        try {
                            $servers = $pelican->listServers($record);
                        } catch (Throwable $e) {
                            $record->update(['status' => 'error']);

                            Notification::make()
                                ->title('Could not reach Pelican')
                                ->body($e->getMessage())
                                ->danger()
                                ->send();

                            return;
                        }

                        $record->update(['status' => 'ok', 'discovered_servers' => $servers]);

                        if (empty($servers)) {
                            Notification::make()
                                ->title('Connected, but no servers found')
                                ->body('This API key has no accessible servers on this panel.')
                                ->warning()
                                ->send();

                            return;
                        }

                        $list = collect($servers)
                            ->map(fn (array $s) => "{$s['name']} — identifier: {$s['identifier']}")
                            ->implode("\n");

                        Notification::make()
                            ->title(count($servers).' server(s) found')
                            ->body($list)
                            ->success()
                            ->persistent()
                            ->send();
                    }),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListConnectorInstances::route('/'),
            'create' => Pages\CreateConnectorInstance::route('/create'),
            'edit' => Pages\EditConnectorInstance::route('/{record}/edit'),
        ];
    }
}
